# Numpy Random Package Explained

***

## Introduction

Numpy.random is a module under Python’s NumPy library. The module consists of a set of functions for generating random numbers. Each function generates random numbers according to different probabilities across different intervals. Numpy.random module includes random data generation functions, permutation and distribution functions, and random generator methods which allow users to select which generator they would like to use. [1] By using the random module, users are able to initiate random arrays with given distribution functions.

## How to install numpy random package

You need Python to run numpy. Numpy can be installed using Python package manager. (pip command)

    pip install numpy

Numpy random package is already included in the numpy package.

In [1]:
import numpy as np

## Simple random data and permutation functions

Simple random data can be obtained using the rand function. This rand function takes in dimensions as parameters and returns random sample data array uniformly distributed between 0 and 1. [2]


In [2]:


np.random.rand(2, 2)

array([[0.52781962, 0.26173865],
       [0.06795762, 0.13414751]])

Another way to obtain random data is to use random_sample function. This function takes dimensions as parameters and returns random float data array.

This function uses cotinuous distribution within the given interval to generate random sample data. It uses the following formula to make this generation. [3]

    (b - a) * random_sample() + a

In [3]:
np.random.random_sample()

0.9063209765525431

In [4]:
type(np.random.random_sample())

float

In [5]:
np.random.random_sample((5,))

array([0.74631595, 0.98283633, 0.7221544 , 0.69689229, 0.57728343])

Random state permutation is another way to create random data. The name of the function is numpy.random.RandomState.permutation. This function takes an array or a value as dimensions to permutate or generate random data. [4]

In [6]:
np.random.permutation(5)

array([4, 0, 1, 2, 3])

In [7]:
np.random.permutation([4, 4, 5, 23, 17])

array([23, 17,  4,  5,  4])

In [8]:
arr = np.arange(10).reshape((5, 2))
np.random.permutation(arr)

array([[8, 9],
       [6, 7],
       [0, 1],
       [4, 5],
       [2, 3]])

numpy.random.RandomState.permutation changes the order of data in a given array while numpy.random.RandomState.random_sample generates a uniformly distributed random data. They are both similiar in so far as the first one leaves the original permutation as is and returns a shuffled version while the second modifies a sequence.

## Distributions

#### Binominal Distribution

    numpy.random.binomial(n, p, size=None)

This function uses binomial distribution to select samples. Samples are taken from a bionomial distributuion with given parameters. n means number of trials/atttempts, p represents probability of succcess, and n must be an integer and greater or equal to 0. p must be in the interval of 0 to 1 [6]

In [12]:
# Example of Coin Tossing Game  8 turns for each game - a 100 games in total. 

n, p = 8, .5       # number of attempts, probability of success

s = np.random.binomial(n, p, 100)  
print (s)

[4 3 3 4 3 4 4 1 3 6 6 4 4 3 2 3 5 5 5 4 4 4 2 6 3 3 4 4 8 4 4 3 3 3 5 5 6
 7 6 3 3 6 6 5 7 4 6 2 6 5 4 5 3 6 3 6 2 3 6 3 7 7 4 2 4 4 4 4 3 3 5 3 3 2
 3 6 4 4 4 4 6 2 4 6 3 2 3 3 5 7 5 5 6 7 3 3 5 5 4 2]


#### Chi Square Distribution 

    numpy.random.chisquare(df, size=None)
    
This function uses chi-square distribution to select samples. df represents independent random variables where they distributed uniformly with the mean 0 and variance is 1. Then they are squared and summed to obtain chi square.

In [1]:
np.random.chisquare(6,9)
array([ 1.89920014,  9.00867716,  3.13710533,  5.62318272])

NameError: name 'np' is not defined

#### Poissio Distribution 

#### Uniform Distribution

#### Weibull Distribution

## Seeds

hey aren't truly random and if you analyze enough of them you will detect a pattern. *

To make the number generator more random, you need to identify a starting position. This is what you call a 'seed'. The seed must be as random as possible. However,the number generator is still predictable overtime as apattern .
.

## References


 1.  https://numpy.org/doc/stable/reference/random/index.html
 2. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.rand.html
 3. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.random_sample.html
 4. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.permutation.html
 5. https://stackoverflow.com/questions/1619627/what-does-seeding-mean
 6. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.binomial.html

