# Numpy Random Package Explained

***

## Introduction

Numpy.random is a module under Python’s NumPy library. The module consists of a set of functions for generating random numbers.Numpy.random module includes random data generation functions, permutation and distribution functions, and random generator methods which allow users to select which generator they would like to use. By using the random module, users are able to initiate random arrays with given distribution functions.

## How to install numpy random package

You need Python to run numpy. Numpy can be installed using Python package manager. (pip command)

    pip install numpy

Numpy random package is already included in the numpy package.

In [3]:
import numpy as np

## Simple random data and permutation functions

Simple random data can be obtained using the rand function. This rand function takes in dimensions as parameters and returns random sample data array uniformly distributed between 0 and 1.


In [4]:


np.random.rand(2, 2)

array([[0.16476224, 0.64716522],
       [0.28597218, 0.60912275]])

Another way to obtain random data is to use random_sample function. This function takes dimensions as parameters and returns random float data array.

This function uses cotinuous distribution within the given interval to generate random sample data. It uses the following formula to make this generation.

    (b - a) * random_sample() + a

In [6]:
np.random.random_sample()

0.7288704914953564

In [7]:
type(np.random.random_sample())

float

In [8]:
np.random.random_sample((5,))

array([0.6477242 , 0.99605761, 0.56844949, 0.48408284, 0.10660361])

Random state permutation is another way to create random data. The name of the function is numpy.random.RandomState.permutation. This function takes an array or a value as dimensions to permutate or generate random data.

In [14]:
np.random.permutation(5)

array([0, 4, 3, 2, 1])

In [15]:
np.random.permutation([4, 4, 5, 23, 17])

array([ 4, 23,  4,  5, 17])

In [19]:
arr = np.arange(10).reshape((5, 2))
np.random.permutation(arr)

array([[4, 5],
       [6, 7],
       [2, 3],
       [0, 1],
       [8, 9]])

numpy.random.RandomState.permutation changes the order of data in a given array while numpy.random.RandomState.random_sample generates a uniformly distributed random data.

## Distributions

5 distribution names

## Seeds

Explanation

## References
1. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.permutation.html
2. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.rand.html
3. https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.random_sample.html

